apiVersion: v1
kind: BuildConfig
metadata:
  labels:
    app: backend-docker
  name: backend-docker
  namespace: myproject
spec:
  output:
    to:
      kind: ImageStreamTag
      name: backend:latest
      namespace: myproject
  postCommit: {}
  resources:
    limits:
      memory: 1Gi
  runPolicy: Serial
  source:
    dockerfile: |-
      FROM wildfly
      MAINTAINER Robert Brem <robert.brem@adesso.ch>
      ADD backend.war $JBOSS_HOME/standalone/deployments/
    binary:
      asFile: backend.war
    type: Docker
  strategy:
    dockerStrategy:
      from:
        kind: ImageStreamTag
        name: wildfly:latest
    type: Docker
  triggers: {}