---
apiVersion: v1
kind: ImageStream
metadata:
  name: postgres
  namespace: myproject
spec:
  tags:
  - annotations:
      supports: postgres
      tags: postgres
      version: "11"
    from:
      kind: DockerImage
      name: centos/postgresql-96-centos7:9.6
    name: "11"
  - annotations:
      supports: postgres
      tags: postgres
    from:
      kind: ImageStreamTag
      name: "11"
    name: latest
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: database
  name: database
  namespace: myproject
spec:
  ports:
  - name: 5432-tcp
    port: 5432
    protocol: TCP
    targetPort: 5432
  selector:
    app: database
    deploymentconfig: database
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
---
apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  labels:
    app: database
  name: database
  namespace: myproject
spec:
  replicas: 1
  selector:
    app: database
    deploymentconfig: database
  strategy:
    rollingParams:
      intervalSeconds: 1
      maxSurge: 25%
      maxUnavailable: 25%
      timeoutSeconds: 600
      updatePeriodSeconds: 1
    type: Rolling
  template:
    metadata:
      labels:
        app: database
        deploymentconfig: database
    spec:
      containers:
      - image: 172.30.1.1:5000/myproject/postgres
        imagePullPolicy: Always
        name: database
        env:
        - name: POSTGRESQL_DATABASE
          value: "database"
        - name: POSTGRESQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: database
              key: user
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: database
              key: password
        ports:
        - containerPort: 5432
          protocol: TCP
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
  test: false
